name: Build, Test, & Push Frontend Image

on:
  repository_dispatch:
    types: [frontend]
  push:
    branches: [main, development]
    paths:
      - "frontend/**"
      - ".github/workflows/front_end.yml"
  workflow_dispatch:
    inputs:
      source_repo:
        description: "Owner/repo of the frontend source repository (e.g., ghGill/newsAppFront)"
        required: true
        default: "ghGill/newsAppFront"
        type: string
      source_ref:
        description: "Git ref to build (branch, tag, or commit SHA, e.g., main, v1.0.0, abc1234)"
        required: true
        default: "main"
        type: string
      app_name:
        description: "Application name used in the Docker image (e.g., newsapp-frontend)"
        required: true
        default: "newsapp-frontend"
        type: string

permissions:
  contents: read
  packages: write

concurrency:
  group: cicd-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  MANIFEST_APP_DEFAULT: newsapp-frontend
  DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USERNAME }}
  MANIFESTS_BRANCH: main
  YQ_VERSION: v4.44.3

jobs:
  build:
    name: Build Frontend Image
    if: >
      github.event_name == 'push' ||
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'repository_dispatch' && github.event.action == 'frontend')
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.ctx.outputs.image }}:${{ steps.compute-tags.outputs.tag }}
      image_repo: ${{ steps.ctx.outputs.image }}
      image_tag_only: ${{ steps.compute-tags.outputs.tag }}
      values_suffix: ${{ steps.deploy.outputs.values_suffix }}
      branch: ${{ steps.compute-tags.outputs.branch }}
      commit: ${{ steps.compute-tags.outputs.commit }}
      src_repo: ${{ steps.ctx.outputs.src_repo }}
      tags: ${{ steps.tags.outputs.tags }}

    steps:
      - name: Checkout (CI/CD repo)
        uses: actions/checkout@v4

      - name: Guard required secrets
        shell: bash
        run: |
          set -euo pipefail
          if [ -z "${{ secrets.DOCKERHUB_USERNAME }}" ] || \
             [ -z "${{ secrets.DOCKERHUB_TOKEN }}" ] || \
             [ -z "${{ secrets.MANIFESTS_REPO }}" ] || \
             [ -z "${{ secrets.GH_TOKEN }}" ]; then
            echo "::error::Missing one or more required secrets"
            exit 1
          fi

      - name: Resolve context
        id: ctx
        shell: bash
        env:
          INP_REPO: ${{ inputs.source_repo }}
          INP_REF:  ${{ inputs.source_ref }}
          INP_APP:  ${{ inputs.app_name }}
          CP_REPO:  ${{ github.event.client_payload.source_repo }}
          CP_REF:   ${{ github.event.client_payload.source_ref }}
          CP_APP:   ${{ github.event.client_payload.app_name }}
        run: |
          set -euo pipefail
          SRC_REPO="${INP_REPO:-${CP_REPO:-ghGill/newsAppFront}}"
          SRC_REF="${INP_REF:-${CP_REF:-${GITHUB_REF_NAME:-main}}}"
          APP="${INP_APP:-${CP_APP:-$MANIFEST_APP_DEFAULT}}"
          IMAGE="${DOCKERHUB_USER}/${APP}"
          {
            echo "src_repo=${SRC_REPO}"
            echo "src_ref=${SRC_REF}"
            echo "app=${APP}"
            echo "image=${IMAGE}"
          } >> "$GITHUB_OUTPUT"

      - name: Checkout frontend source repo
        uses: actions/checkout@v4
        with:
          repository: ${{ steps.ctx.outputs.src_repo }}
          ref: ${{ steps.ctx.outputs.src_ref }}
          path: src

      - name: Prepare build context
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p src/nginx
          if [ -d "frontend/nginx" ]; then
            cp -r frontend/nginx/* src/nginx/
          fi
          if [ -f frontend/Dockerfile ]; then
            cp frontend/Dockerfile src/Dockerfile
          else
            echo "::error::No Dockerfile found"
            exit 1
          fi
          if [ -f frontend/.dockerignore ]; then
            cp frontend/.dockerignore src/.dockerignore
          fi

      - name: Compute image tags
        id: compute-tags
        shell: bash
        run: |
          set -euo pipefail
          COMMIT=$(git -C src rev-parse HEAD)
          SHORT=${COMMIT:0:7}
          REF="${{ steps.ctx.outputs.src_ref }}"
          BASE="${REF##*/}"
          if [[ "$BASE" == "main" || "$BASE" == "master" ]]; then
            TAG="latest-${SHORT}"
            IS_LATEST="true"
          else
            TAG="dev-${SHORT}"
            IS_LATEST="false"
          fi
          {
            echo "commit=${COMMIT}"
            echo "tag=${TAG}"
            echo "is_latest=${IS_LATEST}"
            echo "branch=${BASE}"
          } >> "$GITHUB_OUTPUT"

      - name: Resolve deploy environment
        id: deploy
        shell: bash
        env:
          IS_LATEST: ${{ steps.compute-tags.outputs.is_latest }}
        run: |
          set -euo pipefail
          if [[ "${IS_LATEST}" == "true" ]]; then
            echo "env=prod" >> "$GITHUB_OUTPUT"
            echo "k8s_ns=default" >> "$GITHUB_OUTPUT"
            echo "values_suffix=prod" >> "$GITHUB_OUTPUT"
          else
            echo "env=dev" >> "$GITHUB_OUTPUT"
            echo "k8s_ns=development" >> "$GITHUB_OUTPUT"
            echo "values_suffix=dev" >> "$GITHUB_OUTPUT"
          fi

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Assemble tags
        id: tags
        shell: bash
        env:
          IMAGE: ${{ steps.ctx.outputs.image }}
          TAG:   ${{ steps.compute-tags.outputs.tag }}
          LATEST: ${{ steps.compute-tags.outputs.is_latest }}
        run: |
          set -euo pipefail
          {
            echo "tags<<EOF"
            echo "${IMAGE}:${TAG}"
            if [[ "${LATEST}" == "true" ]]; then
              echo "${IMAGE}:latest"
            fi
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

      - name: Build image for testing
        uses: docker/build-push-action@v6
        with:
          context: ./src
          file: ./src/Dockerfile
          platforms: linux/amd64
          load: true
          push: false
          tags: ${{ steps.tags.outputs.tags }}
          build-args: |
            VITE_SERVER_URL=/api
            VITE_NEWS_INTERVAL_IN_MIN=5
            VITE_FRONTEND_GIT_BRANCH=${{ steps.compute-tags.outputs.branch }}
            VITE_FRONTEND_GIT_COMMIT=${{ steps.compute-tags.outputs.commit }}
          labels: |
            org.opencontainers.image.source=${{ steps.ctx.outputs.src_repo }}
            org.opencontainers.image.revision=${{ steps.compute-tags.outputs.commit }}

      - name: Save context for downstream jobs
        shell: bash
        run: |
          echo "IMAGE_TAG=${{ steps.ctx.outputs.image }}:${{ steps.compute-tags.outputs.tag }}" > context.env
      
      - name: Upload context artifact
        uses: actions/upload-artifact@v4
        with:
          name: job-context-frontend
          path: context.env

  test:
    name: Test Frontend Image
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download context artifact
        uses: actions/download-artifact@v4
        with:
          name: job-context-frontend

      - name: Load context into environment
        shell: bash
        run: cat context.env >> $GITHUB_ENV
      
      - name: Run frontend container and test
        shell: bash
        env:
          GITHUB_RUN_ID: ${{ github.run_id }}
        run: |
          set -euo pipefail
          IMAGE_FULL="${{ env.IMAGE_TAG }}"
          CONTAINER_NAME="ci-test-frontend"
          NET="ci-net-${GITHUB_RUN_ID}"
          MOCK_NAME="ci-backend-mock"

          docker network create "${NET}" >/dev/null 2>&1 || true
          docker run -d --name "${MOCK_NAME}" --network "${NET}" python:3.11-alpine sh -c "python -m http.server 3000" >/dev/null
          
          docker run -d --name "${CONTAINER_NAME}" \
            --network "${NET}" \
            -p "8080:8080" \
            -e BACKEND_SERVICE_HOST="${MOCK_NAME}" \
            -e BACKEND_SERVICE_PORT="3000" \
            "${IMAGE_FULL}"

          echo "Waiting for frontend container to start..."
          sleep 15

          echo "Checking frontend container health..."
          http_code=$(curl -s -o /dev/null -w "%{http_code}" "http://localhost:8080/" || true)
          if [ -n "$http_code" ] && [[ "$http_code" =~ ^(2|3|4)[0-9]{2}$ ]]; then
            echo "Success: frontend responded with HTTP ${http_code}"
          else
            echo "::error::Frontend did not respond correctly. HTTP code: ${http_code}"
            docker logs "${CONTAINER_NAME}"
            exit 1
          fi

      - name: Cleanup containers
        if: always()
        run: |
          echo "Stopping and removing test containers..."
          docker stop ci-test-frontend ci-backend-mock || true
          docker rm ci-test-frontend ci-backend-mock || true
          docker network rm ci-net-${{ github.run_id }} || true

  push-and-update-manifests:
    name: Push Image & Update Manifests
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout (CI/CD repo)
        uses: actions/checkout@v4
        
      - name: Checkout frontend source repo
        uses: actions/checkout@v4
        with:
          repository: ${{ needs.build.outputs.src_repo }}
          ref: ${{ needs.build.outputs.commit }}
          path: src

      - name: Prepare build context
        shell: bash
        run: |
          mkdir -p src/nginx
          if [ -d "frontend/nginx" ]; then cp -r frontend/nginx/* src/nginx/; fi
          if [ -f frontend/Dockerfile ]; then cp frontend/Dockerfile src/Dockerfile; fi
          if [ -f frontend/.dockerignore ]; then cp frontend/.dockerignore src/.dockerignore; fi

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push multi-arch image
        uses: docker/build-push-action@v6
        with:
          context: ./src
          file: ./src/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ needs.build.outputs.tags }}
          build-args: |
            VITE_SERVER_URL=/api
            VITE_NEWS_INTERVAL_IN_MIN=5
            VITE_FRONTEND_GIT_BRANCH=${{ needs.build.outputs.branch }}
            VITE_FRONTEND_GIT_COMMIT=${{ needs.build.outputs.commit }}
          labels: |
            org.opencontainers.image.source=${{ needs.build.outputs.src_repo }}
            org.opencontainers.image.revision=${{ needs.build.outputs.commit }}

      - name: Checkout manifests repo
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.MANIFESTS_REPO }}
          token: ${{ secrets.GH_TOKEN }}
          path: manifests

      - name: Install yq and Helm
        run: |
          sudo wget -qO /usr/local/bin/yq "https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_amd64"
          sudo chmod +x /usr/local/bin/yq
          curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Update manifests
        working-directory: manifests
        env:
          IMAGE_REPO: ${{ needs.build.outputs.image_repo }}
          IMAGE_TAG:  ${{ needs.build.outputs.image_tag_only }}
          SUFFIX:     ${{ needs.build.outputs.values_suffix }}
          BRANCH:     ${{ env.MANIFESTS_BRANCH }}
          K8S_NS:     ${{ needs.build.outputs.k8s_ns }}
        shell: bash
        run: |
          set -euo pipefail
          FRONTEND_FILE="values/frontend/${SUFFIX}.yaml"
          BACKEND_FILE="values/backend/${SUFFIX}.yaml"

          BACKEND_NAME=$(yq -r '.fullnameOverride // .app.name // "backend"' "${BACKEND_FILE}")
          BACKEND_PORT=$(yq -r '.service.port // 3000' "${BACKEND_FILE}")
          BACKEND_HOST="${BACKEND_NAME}.${K8S_NS}.svc.cluster.local"

          yq -i "
            .image.repository = \"${IMAGE_REPO}\" |
            .image.tag = \"${IMAGE_TAG}\" |
            .env.plain.BACKEND_SERVICE_HOST = \"${BACKEND_HOST}\" |
            .env.plain.BACKEND_SERVICE_PORT = \"${BACKEND_PORT}\"
          " "${FRONTEND_FILE}"

          helm lint charts/frontend --values "${FRONTEND_FILE}"

          git remote set-url origin "https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ secrets.MANIFESTS_REPO }}.git"
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin "${BRANCH}"
          git rebase origin/"${BRANCH}" || { git rebase --abort || true; git pull --no-rebase || true; }
          
          git add "${FRONTEND_FILE}"
          git commit -m "ci: frontend ${SUFFIX} -> ${IMAGE_REPO}:${IMAGE_TAG}" || echo "No changes to commit"
          git push origin "${BRANCH}"
