name: Build & Push Frontend Image

on:
  repository_dispatch:
    types: [build-frontend]
  push:
    branches: [main, development]
  workflow_dispatch:
    inputs:
      source_repo:
        description: "Owner/repo of the source (frontend) repository"
        required: true
        default: "ghGill/newsAppFront"
        type: string
      source_ref:
        description: "Ref to build (HEAD, branch, tag, or commit SHA)"
        required: true
        default: "HEAD"
        type: string
      app_name:
        description: "App name used in image name"
        required: true
        default: "newsapp-frontend"
        type: string

permissions:
  contents: read
  packages: write

env:
  MANIFEST_APP_DEFAULT: newsapp-frontend
  DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (this repo / infra)
        uses: actions/checkout@v4

      - name: Resolve context (dispatch or manual)
        id: ctx
        shell: bash
        env:
          INP_REPO: ${{ inputs.source_repo }}
          INP_REF:  ${{ inputs.source_ref }}
          INP_APP:  ${{ inputs.app_name }}
        run: |
          set -euo pipefail
          SRC_REPO="${INP_REPO:-${{ github.event.client_payload.SOURCE_REPO || '' }}}"
          SRC_REF="${INP_REF:-${{ github.event.client_payload.BRANCH_NAME || '' }}}"
          APP="${INP_APP:-${{ github.event.client_payload.APP_NAME || '' }}}"
          [ -z "${SRC_REPO}" ] && SRC_REPO="ghGill/newsAppFront"
          [ -z "${SRC_REF}" ] && SRC_REF="${GITHUB_REF_NAME:-HEAD}"
          [ -z "${APP}" ] && APP="${MANIFEST_APP_DEFAULT}"
          echo "src_repo=${SRC_REPO}" >> $GITHUB_OUTPUT
          echo "src_ref=${SRC_REF}"  >> $GITHUB_OUTPUT
          echo "app=${APP}"          >> $GITHUB_OUTPUT
          IMAGE="${DOCKERHUB_USER}/${APP}"
          echo "image=${IMAGE}"      >> $GITHUB_OUTPUT

      - name: Checkout frontend source repo
        uses: actions/checkout@v4
        with:
          repository: ${{ steps.ctx.outputs.src_repo }}
          ref: ${{ steps.ctx.outputs.src_ref }}
          path: src

      - name: Compute image tags
        id: compute-tags
        shell: bash
        working-directory: src
        run: |
          set -euo pipefail
          COMMIT=$(git rev-parse HEAD)
          SHORT=${COMMIT:0:7}
          BRANCH=$(git rev-parse --abbrev-ref HEAD || echo "")
          if [[ "$BRANCH" == "main" || "$BRANCH" == "master" ]]; then
            TAG="latest-${SHORT}"
            IS_LATEST="true"
          else
            TAG="dev-${SHORT}"
            IS_LATEST="false"
          fi
          echo "commit=${COMMIT}" >> $GITHUB_OUTPUT
          echo "tag=${TAG}" >> $GITHUB_OUTPUT
          echo "is_latest=${IS_LATEST}" >> $GITHUB_OUTPUT
          echo "branch=${BRANCH}" >> $GITHUB_OUTPUT

      - name: Resolve deploy environment
        id: deploy
        shell: bash
        env:
          IS_LATEST: ${{ steps.compute-tags.outputs.is_latest }}
        run: |
          set -euo pipefail
          if [[ "${IS_LATEST}" == "true" ]]; then
            echo "env=prod" >> $GITHUB_OUTPUT
            echo "k8s_ns=default" >> $GITHUB_OUTPUT
            echo "values_suffix=prod" >> $GITHUB_OUTPUT
          else
            echo "env=dev" >> $GITHUB_OUTPUT
            echo "k8s_ns=development" >> $GITHUB_OUTPUT
            echo "values_suffix=dev" >> $GITHUB_OUTPUT
          fi

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Copy nginx config into frontend build context
        run: |
          mkdir -p src/nginx
          cp -r frontend/nginx/* src/nginx/

      - name: Build & Push (multi-arch)
        uses: docker/build-push-action@v6
        with:
          context: ./src
          file: ./frontend/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            VITE_SERVER_URL=/api
            VITE_NEWS_INTERVAL_IN_MIN=5
          tags: |
            ${{ steps.ctx.outputs.image }}:${{ steps.compute-tags.outputs.tag }}
            ${{ steps.compute-tags.outputs.is_latest == 'true' && format('{0}:latest', steps.ctx.outputs.image) || '' }}
          labels: |
            org.opencontainers.image.source=${{ steps.ctx.outputs.src_repo }}
            org.opencontainers.image.revision=${{ steps.compute-tags.outputs.commit }}

      # ---------- GitOps: bump FE image + FE env (proxy to backend) ----------
      - name: Checkout manifests repo
        uses: actions/checkout@v4
        with:
          repository: ${{ vars.MANIFESTS_REPO }}
          token: ${{ secrets.GH_TOKEN }}
          path: manifests

      - name: Install yq
        run: |
          YQ_VERSION=v4.44.1
          sudo wget -qO /usr/local/bin/yq "https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_amd64"
          sudo chmod +x /usr/local/bin/yq

      - name: Update frontend image & proxy env in manifests (nested under frontend:)
        working-directory: manifests
        env:
          IMAGE_REPO: ${{ steps.ctx.outputs.image }}
          IMAGE_TAG:  ${{ steps.compute-tags.outputs.tag }}
          SUFFIX:     ${{ steps.deploy.outputs.values_suffix }}
          K8S_NS:     ${{ steps.deploy.outputs.k8s_ns }}
        shell: bash
        run: |
          set -euo pipefail

          BACKEND_FILE="values/backend/${SUFFIX}.yaml"
          FRONTEND_FILE="values/frontend/${SUFFIX}.yaml"

          # Read backend settings from nested structure
          BACKEND_NAME=$(yq -r '.backend.fullnameOverride // .backend.app.name // "backend"' "${BACKEND_FILE}")
          BACKEND_PORT=$(yq -r '.backend.service.port // 8080' "${BACKEND_FILE}")
          BACKEND_HOST="${BACKEND_NAME}.${K8S_NS}.svc.cluster.local"

          # Write frontend settings under nested structure
          yq -i '
            .frontend.image.repository = strenv(IMAGE_REPO) |
            .frontend.image.tag        = strenv(IMAGE_TAG)  |
            .frontend.env.plain.VITE_SERVER_URL = "/api"     |
            .frontend.env.plain.VITE_NEWS_INTERVAL_IN_MIN = "5" |
            .frontend.env.plain.BACKEND_SERVICE_HOST = strenv(BACKEND_HOST) |
            .frontend.env.plain.BACKEND_SERVICE_PORT = strenv(BACKEND_PORT)
          ' "${FRONTEND_FILE}"

          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add "${FRONTEND_FILE}"
          git commit -m "ci: frontend ${SUFFIX} -> ${IMAGE_REPO}:${IMAGE_TAG}, proxy ${BACKEND_HOST}:${BACKEND_PORT}" || echo "No changes"
          git push origin main

